name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build Image
      - name: Build Docker Image
        run: docker-compose -p ledhcg/temp-av build

        # Test container
      - name: Run Docker Container
        run: docker-compose run -d ledhcg/temp-av
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install requirements
        run: pip install pytest requests
      - name: Run tests
        run: pytest
