version: v1.0
name: LEDHCG
blocks:
  - name: Build
    task:
      secrets:
        - name: ledhcg
      jobs:
        - name: Docker build
          commands:
            - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            - checkout
            - docker-compose build
            - docker tag ledhcg:latest "$DOCKER_USERNAME"/ledhcg:latest
            - docker push "$DOCKER_USERNAME"/ledhcg:latest
            - docker images

  - name: Run & Test Docker image
    task:
      secrets:
        - name: ledhcg
      prologue:
        commands:
          - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          - checkout
          - docker pull "$DOCKER_USERNAME"/ledhcg
          - docker-compose up -d
      jobs:
        - name: Check Running Images
          commands:
            - docker ps
        - name: Run Unit test
          commands:
            - docker exec -it semaphore-pyflask-docker_flasksemaphore_1 python -m unittest
